<?
// Generated by bin/configure.sh from config/templates/gestion-config.php.tmpl
// Do NOT hand-edit. Values flow from config/defaults.env + active profile + local.env.

define('DATABASE_NAME',     'appliceo_php');
define('DATABASE_USER_NAME','appliceo');
define('DATABASE_PASSWORD', 'appliceo123');
define('DATABASE_HOST_NAME','mysql');
define('DATABASE_CHARSET',  'utf8');
define('DB_PREFIX',         'ap_');

define('ABS_PATH_SITE', '/var/www/html');
define('ABS_PATH',      '/var/www/html/gestion');

define('DOMAIN',    'localhost');
define('SUBDOMAIN', '');
define('PORT',      '8443');
define('PROTOCOL',  'https://');
define('ABS_URL',      'https://localhost:8443/gestion');
define('ABS_URL_SITE', 'https://localhost:8443');

define('APP_NAME',    'Appliceo');
define('APP_VERSION', '1.0.0');

define('MAX_CONN_ATTEMPTS',     5);
define('BLOCKED_IP_DURATION',   30);
define('RECOVERY_LINK_DURATION', 10);

define('SMTP_HOST',   'mailhog');
define('SMTP_PORT',   1025);
define('SMTP_USER',   '');
define('SMTP_PASS',   '');
define('SMTP_SECURE', '');

if (!defined('ENVIRONMENT')) {
    $host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : '';
    if ($host === 'localhost' || strpos($host, 'localhost') !== false || strpos($host, '127.0.0.1') !== false || strpos($host, 'dev.appliceo.com') !== false || strpos($host, 'apache') !== false) {
        define('ENVIRONMENT', 'development');
    } elseif (strpos($host, 'staging') !== false || strpos($host, 'stg.') !== false) {
        define('ENVIRONMENT', 'staging');
    } else {
        define('ENVIRONMENT', 'production');
    }
}
if (!defined('DEBUG_MODE'))     define('DEBUG_MODE',     ENVIRONMENT !== 'production');
if (!defined('DISPLAY_ERRORS')) define('DISPLAY_ERRORS', ENVIRONMENT !== 'production');

define('MAX_FILE_SIZE', 67108864);
define('UPLOAD_PATH',   '/var/www/html/gestion/uploads/');

define('LOG_PATH',  '/var/www/html/gestion/logs/');
define('ERROR_LOG', '/var/www/html/gestion/logs/error.log');

define('MAX_GUARANTORS_PER_LEASE', 4);

define('DEV_AUTO_LOGIN',         true);
define('DEV_AUTO_LOGIN_USER_ID', 347);
?>
